name: Planetravel
on:
  push:
    branches: [planetravel]
  pull_request:
    branches: [planetravel]
jobs:
  build:
  env:
    CI: true
    strategy:
      matrix: 
        node-version:[16.x,14.x,20.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js version ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      - run:  npm install
      - run:  npm run buildv --prefix planetravel


